ROOT    := $(realpath ../../..)
DEPS    := 
TYPE    := exe
SUBDIRS :=
PRE_BUILD := SUPERMMC.rom
EXTRA_CLEAN := SUPERMMC.rom

-include $(ROOT)/common/top.mk

SUPERMMC.rom:
	wget http://swhs.home.xs4all.nl/bbc/mmbeeb/DFS4C/SUPERMMC.rom
